### ISSUE TITLE
TypeError: component.logVerbose is not a function

### ISSUE THREAD

**Issue by TastefulElk** [serverless/compose#129]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The refactor in version 1.1.0 seems to have broken all service-specific compose commands. Verified that the exact same commands and exact same config work in 1.0.3

### Service configuration (serverless-compose.yml) content

```yaml
services:
  service-a:
    path: service-a
```

### Command name and used flags

serverless service-a:logs

### Command output

```shell
$ /Users/seb/code/blogs/stateful-stack/bug-repo/node_modules/.bin/serverless-compose service-a:logs
Environment: darwin, node 16.13.1, compose 1.1.0
Docs:        slss.io/docs-compose
Bugs:        github.com/serverless/compose/issues

Error:
TypeError: component.logVerbose is not a function
    at ComponentsService.invokeComponentCommand (/Users/seb/code/blogs/stateful-stack/bug-repo/node_modules/@serverless/compose/src/ComponentsService.js:392:17)
    at async runComponents (/Users/seb/code/blogs/stateful-stack/bug-repo/node_modules/@serverless/compose/src/index.js:133:7)
```

**Comment by pgrzesik** [comment]
Thanks a lot for detailed report @TastefulElk - I have a fix ready, it will be published soon

**Comment by pgrzesik** [comment]
Update: fix published with v1.1.1 - sorry for the trouble @TastefulElk

**Comment by TastefulElk** [comment]
Thanks for the quick fix!

**Comment by mnapoli** [comment]
Hey @TastefulElk just noticed your Slack message as well, thanks for the report and @pgrzesik for the quick fix, I must confess that was all my fault 😅
